### ISSUE TITLE
Issue with specifying prior weights

### ISSUE THREAD

**Issue by hsomineni** [stephenslab/susieR#102] opened 2020-03-31 00:31 UTC
Hi Gao. Do you know what might be causing this error? It worked just fine without "prior_weights". Now that I am specifying a vector of prior causal probabilities, I've been getting this error. Thanks a lot for your time.

<img width="585" alt="Screen Shot 2020-03-31 at 12 43 31 PM" src="https://user-images.githubusercontent.com/32373650/78053402-8c7f0780-734e-11ea-9e6b-3f4388690b27.png">

**Comment by zouyuxin** [comment] 2020-03-31 00:44
Thanks for reporting the issue. Could you send us an example that reproduces the problem?

**Comment by gaow** [comment] 2021-11-10 00:03
Close this ticket due to a lack of follow up.

**Closed by gaow** 2021-11-10 00:03 UTC
