### ISSUE TITLE
If I have binary response, is it still possible to use SusieR as a linear probability model instead of a linear regression mode?

### ISSUE THREAD

**Issue by garyzhubc** [stephenslab/susieR#205] opened 2023-11-07 03:07 UTC
If I have binary response, is it still possible to use SusieR as a linear probability model instead of a linear regression model?

**Comment by gaow** [comment] 2023-12-29 15:32
this is duplicate of #208 and has been discussed in various tickets in this repo (eg #74 ) in addition to SuSiE RSS paper

**Closed by gaow** 2023-12-29 15:32 UTC
