### ISSUE TITLE
check_null_threshold

### ISSUE THREAD

**Issue by jerome-f** [stephenslab/susieR#197] opened 2023-07-13 04:51 UTC
Hi,

what is the behavior of check_null_threshold=0 from the previous commits this was changed from check_null_tol=0.1, how does it affect the credible sets? The explanation in docs is cryptic. Is setting check_null_threshold=0.1 more strict? i.e. will lead to less false discoveries? 

Best
Jerome

**Comment by jerome-f** [comment] 2023-07-13 05:49
reason I am bringing this up is cos I am running into a issue 

```
Error in if (loglik(0, betahat, shat2, prior_weights) + check_null_threshold >=  : 
  missing value where TRUE/FALSE needed
Calls: susie ... single_effect_regression -> optimize_prior_variance
Execution halted
```

susie ran with individual level data (pheno and dosage) with the following setting:
```
susie( X, y, L = 30, \
       estimate_prior_method = "EM", \
       verbose = T, refine = T, max_iter = 1000) 
```

**Comment by pcarbo** [comment] 2023-07-16 16:58
@jerome-f Just to check whether the problem is indeed due to estimating the prior variance, does the error go away if you set `estimate_prior_variance = FALSE`?

Setting `check_null_threshold > 0 ` will have the effect of pruning the CSs slightly more aggressively.

**Comment by jerome-f** [comment] 2023-07-17 02:29
Setting the gave `estimate_prior_variance = FALSE` me an error in ELBO 
```
[1] "objective:-34159.5469366425"
[1] "objective:-34159.546639484"
Error in if ((elbo[i + 1] - elbo[i]) < tol) { : 
  missing value where TRUE/FALSE needed
Calls: susie -> susie
Execution halted 
```

**Comment by pcarbo** [comment] 2023-07-17 03:21
@jerome-f So the issue does not seem to be the estimation of the prior.
If you set L to a smaller value, such as L = 10, does it still produce an error?

**Comment by jerome-f** [comment] 2023-07-17 15:09
Set the L=5 and still get the same errors. elbo[i+1] is going to NA, and likely checking for it somewhere in the eblo module or single_effect_regression module might help catching this.

**Comment by pcarbo** [comment] 2023-07-17 15:12
Okay, thanks for troubleshooting. If you can share your data set here, or by email if you prefer, we would be happy to track down the exact source of the error and update susieR with a more useful error message.

**Comment by pcarbo** [comment] 2023-07-18 02:44
Thanks, I've requested access to your data set under my uchicago email address.

**Comment by jerome-f** [comment] 2023-07-18 02:47
Just granted you access. Let me know if you have trouble accessing

**Comment by pcarbo** [comment] 2023-07-18 02:48
@jerome-f Thanks — can you please instead share this as an `.RData` file with the inputs needed to call susie (X, y)?

**Comment by jerome-f** [comment] 2023-07-18 02:51
Also the same data was finemapped with FINEMAP resulting in 9 credible sets (8.9). Also this data is among the loci that takes forever to converge

**Comment by jerome-f** [comment] 2023-07-18 04:36
@pcarbo shared `[file](https://drive.google.com/file/d/1Q1hSLdyO7qdCEr2YtfjN1I9q8_2bHhyS/view?usp=drive_link)` in .rds 

```
data <- readRDS("annonymized_data_for_test.rds")
fit <- susie(as.matrix( data[, -seq( 2 ), with = F ] ), data[[ 2 ]], 
               L = 10, estimate_prior_method = "EM", 
               verbose = T, refine = T, max_iter = 1000)
```

**Comment by pcarbo** [comment] 2023-07-19 04:43
@jerome-f I ran this and it worked (no error):

```r
library(susieR)
set.seed(1)
dat <- readRDS("annonymized_data_for_test.rds")
X <- as.matrix(dat[,-c(1,2)])
y <- dat$PHENOTYPE
fit <- susie(X,y,L = 10, estimate_prior_method = "EM",
             verbose = TRUE,refine = FALSE,max_iter = 10)
```

However, when I set `refine = TRUE` then I got an error:

```
Error in if (loglik(0, betahat, shat2, prior_weights) + check_null_threshold >=  :
  missing value where TRUE/FALSE needed
```

Can you confirm? 

Note I am using susieR 0.12.37.

**Comment by jerome-f** [comment] 2023-07-19 05:25
@pcarbo I will try with `refine = FALSE` I ran with refine=TRUE so something is going wrong in the refinement step?

**Comment by pcarbo** [comment] 2023-07-19 16:57
@jerome-f Yes, exactly, there must be a bug somewhere in the refinement step. If you don't mind, I will leave this Issue open as a reminder to fix the bug.

**Comment by jerome-f** [comment] 2023-07-20 06:02
Thanks and yes please keep this open

**Comment by pcarbo** [comment] 2023-10-02 16:13
@jerome-f Apologies for the delay. This should be fixed now. Can you please try again with the latest version of `susieR` on GitHub?

**Comment by jerome-f** [comment] 2023-10-02 16:34
Will try it out. Thanks for fixing this.

**Comment by jerome-f** [comment] 2023-10-02 21:55
Hi Peter,

The bug is fixed and I think we can close this. 

Best
Jerome

**Comment by pcarbo** [comment] 2023-10-03 01:45
Thanks for checking.

**Closed by pcarbo** 2023-10-03 01:45 UTC
